/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hoc;

import java.io.StringReader;
import java_cup.runtime.Symbol;

/**
 *
 * @author chori
 */
public class IDE extends javax.swing.JFrame {

    NumeroLinea numerolinea;
    Directorio dir;
    /**
     * Creates new form IDE
     */
    public IDE() {
        initComponents();
        inicializar();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnTokens = new javax.swing.JButton();
        btnCompilar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpCode = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaCompile = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/Icon/icons8_code_file_48px.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Nuevo documento");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/On Layer/icons8_code_file_48px_on.png"))); // NOI18N
        btnNuevo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/pressed/icons8_code_file_48px_p.png"))); // NOI18N
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 80, 80));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/Icon/icons8_save_48px.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar documento");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/On Layer/icons8_save_48px_on.png"))); // NOI18N
        btnGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/pressed/icons8_save_48px_p.png"))); // NOI18N
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 80, 80));

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/Icon/icons8_opened_folder_48px.png"))); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setToolTipText("Abrir documento");
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/On Layer/icons8_opened_folder_48px_ON.png"))); // NOI18N
        btnAbrir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/pressed/icons8_opened_folder_48px_P.png"))); // NOI18N
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 80, 80));

        btnTokens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/Icon/icons8-index-48.png"))); // NOI18N
        btnTokens.setText("Tokens");
        btnTokens.setToolTipText("Abrir documento");
        btnTokens.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTokens.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/On Layer/icons8-index-48.png"))); // NOI18N
        btnTokens.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/pressed/icons8-index-48.png"))); // NOI18N
        btnTokens.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokensActionPerformed(evt);
            }
        });
        getContentPane().add(btnTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 80, 80));

        btnCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/Icon/icons8_code_48px.png"))); // NOI18N
        btnCompilar.setText("Sintáctico");
        btnCompilar.setToolTipText("Palabras reservadas");
        btnCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompilar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/On Layer/icons8_code_48px_on.png"))); // NOI18N
        btnCompilar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/hoc/Iconos/pressed/icons8_code_48px_p.png"))); // NOI18N
        btnCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 80, 80));

        jtpCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtpCodeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtpCode);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 1000, 400));

        jtaCompile.setColumns(20);
        jtaCompile.setRows(5);
        jScrollPane2.setViewportView(jtaCompile);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 1270, 120));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 140, 250, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        jtaCompile.setText("");
        dir.Nuevo(this);
        clearAllComp();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
         dir.Guardar(this);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
         dir.Abrir(this);
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokensActionPerformed
    
    // 1) Limpiamos el área donde vamos a mostrar los tokens
    jTextArea1.setText("");

    try {
        // 2) Obtenemos el texto fuente del editor
        String input = jtpCode.getText().trim();

        // 3) Creamos el analizador léxico con ese texto
        //    (Asegúrate de importar la clase generada por JFlex)
        AnalizadorLexico scanner = new AnalizadorLexico(new StringReader(input));

        // 4) Leemos los tokens uno a uno
        Symbol currentToken;
        int tokenCount = 1;  // Contador para enumerar cada token leído

        while (true) {
            // next_token() analiza y devuelve un Symbol (o null si no hay más)
            currentToken = scanner.next_token();

            if (currentToken == null) {
                // Si el analizador retorna null, no hay más tokens
                break;
            }

            // El código del token es currentToken.sym
            int tokenCode = currentToken.sym;

            if (tokenCode == AnalizadorSintacticoSym.EOF) {
                // Podemos mostrarlo si queremos
                jTextArea1.append(
                    "#" 
                    + "TOKEN CODE: " + tokenCode
                    + "\tNAME: EOF"
                    + "\n"
                );
                // Rompemos el bucle si detectamos EOF
                break;
            }

            // 5) Nombre textual del token (por ejemplo, "NUM", "VAR", "OpSuma", etc.)
            String tokenName = AnalizadorSintacticoSym.terminalNames[tokenCode];

            // 6) Obtenemos el lexema con scanner.yytext()
            //    (sin usar currentToken.value)
            String lexema = scanner.yytext();

            // 7) Mostramos la información con el formato que desees
            jTextArea1.append(
                "#"
                + "TOKEN CODE: " + tokenCode 
                + "\tNAME: " + tokenName 
                + "\tLEXEMA: " + lexema
                + "\n"
            );

            tokenCount++;
        }

        // Mensaje opcional al final del análisis
        jTextArea1.append(">> Análisis léxico finalizado.\n");

    } catch (Exception ex) {
        jTextArea1.append("Error: " + ex.getMessage() + "\n");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnTokensActionPerformed

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        // Limpiamos el área de compilación si deseas
        jtaCompile.setText("");
        this.btnTokensActionPerformed(evt);

        try {
            // Texto a analizar
            String input = jtpCode.getText().trim();

            // Creamos el analizador léxico
            AnalizadorLexico scanner = new AnalizadorLexico(new StringReader(input));

            // Creamos el analizador sintáctico y le inyectamos el léxico
            AnalizadorSintactico parser = new AnalizadorSintactico(scanner);

            // Inyectamos la referencia de esta interfaz al parser
            parser.setIDE(this);

            // Ejecutamos el parse
            parser.parse();

            // Si llega acá sin excepción, se completó el parse
            jtaCompile.append(">> Análisis sintáctico finalizado sin errores.\n");

        } catch (Exception ex) {
            jtaCompile.append("Error: " + ex.getMessage() + "\n");
            ex.printStackTrace();
        }  
    }//GEN-LAST:event_btnCompilarActionPerformed

    private void jtpCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpCodeKeyReleased
        // TODO add your handling code here:
         int keyCode = evt.getKeyCode();

        if ((keyCode >= 65 && keyCode <= 90) || (keyCode >= 48 && keyCode <= 57) 
            || (keyCode >= 97 && keyCode <= 122) || (keyCode != 27 && !(keyCode >= 37 
            && keyCode <= 40) && !(keyCode >= 16 && keyCode <= 18) && keyCode != 524 
            && keyCode != 20)) {

            if (!getTitle().contains("*")) {
                setTitle(getTitle() + "*");
            }
        }
    }//GEN-LAST:event_jtpCodeKeyReleased

    /**
     * @param args the command line arguments
     */
    
    private void inicializar(){
        
        dir = new Directorio();
        
        //Importante
        setTitle("#EmptyStack");
        String[] options = new String[]{"Guardar y continuar", "Descartar"};
        
        //Numero de linea
        numerolinea = new NumeroLinea(jtpCode);
        jScrollPane1.setRowHeaderView(numerolinea);
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDE().setVisible(true);
            }
        });
    }
    
    public void clearAllComp(){
        jtaCompile.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnTokens;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextArea jtaCompile;
    public javax.swing.JTextPane jtpCode;
    // End of variables declaration//GEN-END:variables
}
